mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

mysite/pybo/urls.py
from django.urls import path
from .views import app_views, base_views, customapp_views, gitapp_views, project_views, monitor_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:project_id>/', base_views.detail, name='detail'),
    
    # project_views.py
    path('project/', project_views.project, name='project'),
    path('project/delete/<int:project_id>/', project_views.project_delete, name='project_delete'),
    
    # app_views.py
    path('app/', app_views.app, name='app'),
    path('webapp/', app_views.webapp, name='webapp'),
    path('dbapp/', app_views.dbapp, name='dbapp'),

    # custom_views.py
    path('jenkins_api/', customapp_views.jenkins_api, name='jenkins_api'),
    path('jenkins_backup/', customapp_views.jenkins_backup, name='jenkins_backup'),
    path('customapp/', customapp_views.customapp, name='customapp'),

    # gitapp_views.py
    path('docker/<int:project_id>/', gitapp_views.docker, name='docker'),
    path('docker/create/<int:project_id>', gitapp_views.create_jenkins, name='create_jenkins'),
    path('YAML/<int:project_id>/', gitapp_views.argocd, name='argocd'),
    path('github_list/<int:project_id>/', gitapp_views.github_listfile, name='github_listfile'),
    path('github_list/create/<int:project_id>', gitapp_views.github_createfile, name='github_createfile'),
    path('github_list/edit/<int:project_id>', gitapp_views.github_editfile, name='github_editfile'),
    path('github_list/delete/<int:project_id>', gitapp_views.github_deletefile, name='github_deletefile'),

    # monitor_views.py
    path('monitor/<int:project_id>', monitor_views.monitor_list, name='monitor_list'),
    path('logging/', monitor_views.logging, name='logging'),
    path('grafana/', monitor_views.grafana, name='grafana'),
]

mysite/pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Project
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from ..forms import ProjectForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import pymysql
from time import sleep
import jenkins
import requests
import json


def index(request):
    project = Project.objects.all()
    context = {'project': project, 'state' : ''}
    return render(request, 'pybo/mainpage.html', context) 

def detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    context = {'project': project, 'state' : ''}
    if project.KIND == 'App':
        return render(request, 'pybo/appcreate.html', context)
    elif project.KIND == 'Custom App':
        return render(request, 'pybo/custom.html', context)
    elif project.KIND == 'GitHub App':
        return render(request, 'pybo/github.html', context)
    else:
        context = {'project': project, 'state' : '오류'}
        return render(request, 'pybo/mainpage.html', context)

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon_io/favicon.ico' %}"/>
    <title>Auto K8s</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<div>
    <br><br><br>
</div>
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!--J Query-->
<script src="{% static 'jquery-3.6.1.min.js' %}"></script>
</body>
</html>

mysite/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

mysite/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light navbar-light border-bottom fixed-top">
  <div class="container-fluid">
    <a draggable="false" class="navbar-brand" style="color:slateblue;" href="{% url 'pybo:index' %}">
      <img src="{% static 'favicon_io/android-chrome-512x512.png' %}" alt="" style="height: 40px;" draggable="false">
    </a>
    <button class="navbar-toggler" type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a draggable="false" class="nav-link" style="color:indigo;" href="{% url 'pybo:project' %}">프로젝트</a>
        </li>
        <li class="nav-item">
          <a draggable="false" class="nav-link" style="color:indigo;" href="{% url 'pybo:grafana' %}">K8s Monitor</a>
        </li>
        <li class="nav-item">
          <a draggable="false" class="nav-link" style="color:indigo;" href="{% url 'pybo:logging' %}">Logging</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled">쿠버네티스 기반 애플리케이션 자동 생성</a>
        </li>
      </ul>
    </div>
  </div>
</nav>