mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

mysite/pybo/urls.py
from django.urls import path
from .views import app_views, base_views, customapp_views, gitapp_views, project_views, monitor_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:project_id>/', base_views.detail, name='detail'),
    
    # project_views.py
    path('project/', project_views.project, name='project'),
    path('project/delete/<int:project_id>/', project_views.project_delete, name='project_delete'),
    
    # app_views.py
    path('app/', app_views.app, name='app'),
    path('webapp/', app_views.webapp, name='webapp'),
    path('dbapp/', app_views.dbapp, name='dbapp'),

    # custom_views.py
    path('jenkins_api/', customapp_views.jenkins_api, name='jenkins_api'),
    path('jenkins_backup/', customapp_views.jenkins_backup, name='jenkins_backup'),
    path('customapp/', customapp_views.customapp, name='customapp'),

    # gitapp_views.py
    path('docker/<int:project_id>/', gitapp_views.docker, name='docker'),
    path('docker/create/<int:project_id>', gitapp_views.create_jenkins, name='create_jenkins'),
    path('YAML/<int:project_id>/', gitapp_views.argocd, name='argocd'),
    path('github_list/<int:project_id>/', gitapp_views.github_listfile, name='github_listfile'),
    path('github_list/create/<int:project_id>', gitapp_views.github_createfile, name='github_createfile'),
    path('github_list/edit/<int:project_id>', gitapp_views.github_editfile, name='github_editfile'),
    path('github_list/delete/<int:project_id>', gitapp_views.github_deletefile, name='github_deletefile'),

    # monitor_views.py
    path('monitor/<int:project_id>', monitor_views.monitor_list, name='monitor_list'),
    path('logging/', monitor_views.logging, name='logging'),
    path('grafana/', monitor_views.grafana, name='grafana'),
]

mysite/pybo/forms.py
from django import forms
from pybo.models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['NAME', 'KIND', 'GIT', 'GITTOKEN', 'SONARTOKEN']
        labels = {
            'NAME' : '이름',
            'KIND' : '종류',
            'GIT' : '주소',
            'GITTOKEN' : 'GIT 토큰',
            'SONARTOKEN' : 'SONAR 토큰'
        }

mysite/pybo/views/app_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Project
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from ..forms import ProjectForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import pymysql
from time import sleep
import jenkins
import requests
import json

project_name = "project"
argo_host = "http://argocd.xyz/"
request_url1 = """{}api/v1/session""".format(argo_host)
data1 = {'username':'admin','password':'python3.10'}
api_response = requests.post(request_url1, data=json.dumps(data1))
argocd_accesstoken = api_response.json()['token']

def app(request):
    return render(request, 'pybo/appcreate.html')

def webapp(request):
    """, project_name, app_name, parameter0, parameter1, parameter2, parameter3
        argocd application 생성
        파라미터:
            argocd_host: argocd 주소
            argocd_access_token: argocd 액세스 토큰
            argocd_project_name: 배포할 argocd 프로젝트 이름
            app_name: 배포할 앱 이름
            deploy_kubernetes_namespace: 배포할 쿠버네티스 namespace
            app_git_remoterepo: argocd가 배포할 앱 git 주소
        리턴:
            True: 생성성공
            False: 생성실패
    """
    flag = 0
    pj = Project.objects.values()
    for i in range(0, len(pj)):
        if pj[i]['id'] == int(request.POST['PID']):
            project = pj[i]
            flag = 1
            break
    if flag == 0:
        print("Project doesn't exist")
    
    if 'web' in request.POST:
        response = False
        helm_value0 = f"{request.POST['WNAME']}"
        helm_value1 = f"{request.POST['WPW']}"
        if request.POST['web'] == "tomcat":
            helm_repo = "https://charts.bitnami.com/bitnami"
            helm_version = "10.5.7"
        else:
            helm_repo = "https://charts.bitnami.com/bitnami"
            helm_version = "15.2.22"
        data = {
            "apiVersion": "argoproj.io/v1alpha1",
            "kind": "Application",
            "metadata": 
                { 
                    "name": "%s-%s" % (request.POST['PN'], request.POST['web']) 
                },
            "spec": {
                "destination": {
                    "name": "",
                    "namespace": f"{request.POST['PN']}",
                    "server": "https://kubernetes.default.svc"
                },
                "source": {
                    "path": "",
                    "repoURL": f"{helm_repo}",
                    "targetRevision": f"{helm_version}",
                    "chart" : f"{request.POST['web']}",
                    "helm" : { 
                        "parameters": [
                            { "name" : f"{request.POST['web']}" + "Username", "value" : f"{helm_value0}"},
                            { "name" : f"{request.POST['web']}" + "Password", "value" : f"{helm_value1}"},
                            { "name" : "service.type", "value" : "ClusterIP"},
                            { "name" : "ingress.enabled", "value" : "true"},
                            { "name" : "ingress.hostname", "value" : "%s%s.xyz" %(request.POST['PN'], request.POST['web'])},
                            { "name" : "ingress.annotations", "value" : 'kubernetes.io/ingress.class: "nginx"'},
                        ]
                    }
                },
                "project": f"{request.POST['PN']}",
                "syncPolicy": {
                    "automated": {},
                    "syncOptions": ["CreateNamespace=true", "ApplyOutOfSyncOnly=true"]
                }
            }
        }
        try:
            request_url = """{}api/v1/applications""".format(argo_host)
            headers = {"Authorization": "Bearer {}".format(argocd_accesstoken)}
            api_response = requests.post(request_url, data=json.dumps(data), headers=headers)
            context = {'project' : project, 'url' : "%s%s.xyz" %(request.POST['PN'], request.POST['web']), 'state' : ''}

            if api_response.ok:
                response = True
                print(f"argocd 애플리케이션 생성 성공: {project_name}")
            else:
                print("[332] create argocd application is failed: {}".format(api_response.json()))

        except Exception as e:
            print("[332] create argocd application is failed: {}".format(e))
        finally:
            return render(request, 'pybo/appcreate.html', context)
    else:
        context = {'project' : project, 'state' : 'None'}
    return render(request, 'pybo/appcreate.html', context)

    


def dbapp(request):
    """, project_name, app_name, parameter0, parameter1, parameter2, parameter3
        argocd application 생성
        파라미터:
            argocd_host: argocd 주소
            argocd_access_token: argocd 액세스 토큰
            argocd_project_name: 배포할 argocd 프로젝트 이름
            app_name: 배포할 앱 이름
            deploy_kubernetes_namespace: 배포할 쿠버네티스 namespace
            app_git_remoterepo: argocd가 배포할 앱 git 주소
        리턴:
            True: 생성성공
            False: 생성실패
    """
    flag = 0
    pj = Project.objects.values()
    for i in range(0, len(pj)):
        if pj[i]['id'] == int(request.POST['PID']):
            flag = 1
            project = pj[i]
            break
    if flag == 0:
        print("Project doesn't exist")

    if 'db' in request.POST:
        response = False
        helm_value0 = f"{request.POST['RPW']}"
        helm_value1 = f"{request.POST['UID']}"
        helm_value2 = f"{request.POST['UPW']}"
        helm_value3 = f"{request.POST['DB']}"
        if request.POST['db'] == "mariadb":
            helm_repo = "https://charts.bitnami.com/bitnami"
            helm_version = "11.4.2"
        else:
            helm_repo = "https://charts.bitnami.com/bitnami"
            helm_version = "9.4.6"
        data = {
            "apiVersion": "argoproj.io/v1alpha1",
            "kind": "Application",
            "metadata": 
                { 
                    "name": "%s-%s" % (request.POST['PN'], request.POST['db'])
                },
            "spec": {
                "destination": {
                    "name": "",
                    "namespace": f"{request.POST['PN']}",
                    "server": "https://kubernetes.default.svc"
                },
                "source": {
                    "path": "",
                    "repoURL": f"{helm_repo}",
                    "targetRevision": f"{helm_version}",
                    "chart" : f"{request.POST['db']}",
                    "helm": { 
                        "parameters": [
                            { "name" : "auth.rootPassword", "value" : f"{helm_value0}"},
                            { "name" : "auth.username", "value" : f"{helm_value1}"},
                            { "name" : "auth.password", "value" : f"{helm_value2}"},
                            { "name" : "auth.database", "value" : f"{helm_value3}"},
                            { "name" : "networkPolicy.enabled", "value" : "true" },
                            { "name" : "networkPolicy.allowExternal", "value" : "true" },
                        ]
                    }
                },
                "project": f"{request.POST['PN']}",
                "syncPolicy": {
                    "automated": {},
                    "syncOptions": ["CreateNamespace=true", "ApplyOutOfSyncOnly=true"]
                }
            }
        }
        try:
            request_url = """{}api/v1/applications""".format(argo_host)
            headers = {"Authorization": "Bearer {}".format(argocd_accesstoken)}
            api_response = requests.post(request_url, data=json.dumps(data), headers=headers)
            context = {'project' : project, 'url' : "%s%s.xyz" %(request.POST['PN'], request.POST['db']), 'state' : ''}

            if api_response.ok:
                response = True
                print(f"argocd 애플리케이션 생성 성공: {project_name}")
            else:
                print("[332] create argocd application is failed: {}".format(api_response.json()))

        except Exception as e:
            print("create argocd application is failed: {}".format(e))
        finally:
            return render(request, 'pybo/appcreate.html', context)
    else:
        context = {'project' : project, 'state' : 'None'}
    return render(request, 'pybo/appcreate.html', context)

    

mysite/pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Project
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from ..forms import ProjectForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import pymysql
from time import sleep
import jenkins
import requests
import json


def index(request):
    project = Project.objects.all()
    context = {'project': project, 'state' : ''}
    return render(request, 'pybo/mainpage.html', context) 

def detail(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    context = {'project': project, 'state' : ''}
    if project.KIND == 'App':
        return render(request, 'pybo/appcreate.html', context)
    elif project.KIND == 'Custom App':
        return render(request, 'pybo/custom.html', context)
    elif project.KIND == 'GitHub App':
        return render(request, 'pybo/github.html', context)
    else:
        context = {'project': project, 'state' : '오류'}
        return render(request, 'pybo/mainpage.html', context)

mysite/pybo/views/customapp_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from ..models import Project
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from ..forms import ProjectForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import pymysql
from time import sleep
import jenkins
import requests
import json

host = "http://192.168.160.244:8080"
username = "admin" #jenkins username here
password = "admin" # Jenkins user password / api token here
server = jenkins.Jenkins(host, username=username, password=password)

project_name = "project"
argo_host = "http://argocd.xyz/"
request_url1 = """{}api/v1/session""".format(argo_host)
data1 = {'username':'admin','password':'python3.10'}
api_response = requests.post(request_url1, data=json.dumps(data1))
argocd_accesstoken = api_response.json()['token']

def jenkins_api(request):
    addr = request.POST['addr']
    pj = Project.objects.values()
    flag = 0
    for i in range(0, len(pj)):
        if pj[i]['id'] == int(request.POST['PID']):
            project = pj[i]
            flag = 1
            break
    if flag == 0:
        print("Project doesn't exist")
    
    myConfig = server.get_job_config(request.POST['PN'])
    # github 주소가 등록되어 있지 않으면
    if "<url>https://github.com/</url>" in myConfig:
        new = myConfig.replace('<url>https://github.com/</url>', '<url>%s</url>' %(addr))
        server.reconfig_job(request.POST['PN'], new)
        server.build_job(request.POST['PN'])
        context = {'state' : '빌드 완료', 'project' : project}
        
    # 해당 github 주소가 이미 등록되어 있는 상태면   
    elif "<url>{}</url>".format(addr) in myConfig: 
        server.build_job(request.POST['PN'])
        context = {'state' : '빌드 완료', 'project' : project}
        
    # 다른 github 주소가 이미 등록되어 있는 상태면    
    else:
        context = {'state' : '이미 Github 레포지토리가 등록되어 있습니다. 다른 레포지토리를 사용하시려면 프로젝트를 새로 생성히세요.', 'project' : project}    

    if request.POST['KIND'] == 'GitHub App':
        return render(request, 'pybo/github.html', context)
    else:
        return render(request, 'pybo/custom.html', context)

def jenkins_backup(request):
    init = open('./init_conf', 'r')
    f = init.read()
    server.reconfig_job('test', f)
    init.close()
    return redirect('pybo:index')

def customapp(request):
    """, project_name, app_name, parameter0, parameter1, parameter2, parameter3
        argocd application 생성
        파라미터:
            argocd_host: argocd 주소
            argocd_access_token: argocd 액세스 토큰
            argocd_project_name: 배포할 argocd 프로젝트 이름
            app_name: 배포할 앱 이름
            deploy_kubernetes_namespace: 배포할 쿠버네티스 namespace
            app_git_remoterepo: argocd가 배포할 앱 git 주소
        리턴:
            True: 생성성공
            False: 생성실패
    """

    pj = Project.objects.values()

    flag = 0
    for i in range(0, len(pj)):
        if pj[i]['id'] == int(request.POST['PID']):
            project = pj[i]
            flag = 1
            break
    if flag == 0:
        print("Project doesn't exist")
        context = {'project': project, 'state' : '오류'}
        return render(request, 'pybo/mainpage.html', context)

    response = False
    GitURL = f"{request.POST['ADDR']}"
    GitFolder = f"{request.POST['GIT']}"
    data = {
        "apiVersion": "argoproj.io/v1alpha1",
        "kind": "Application",
        "metadata": 
            { 
                "name": f"{request.POST['PN']}" 
            },
        "spec": {
            "destination": {
                "name": "",
                "namespace": f"{request.POST['PN']}",
                "server": "https://kubernetes.default.svc"
            },
            "source": {
                "path": f"{GitFolder}",
                "repoURL": f"{GitURL}",
                "targetRevision": "main",
                "directory": {
                    "recurse": True,
                },
            },
            "project": f"{request.POST['PN']}",
            "syncPolicy": {
                "automated": {},
                "syncOptions": ["CreateNamespace=true"]
            }
        }
    }
    context = {'project' : project, 'state' : '배포 완료'}
    try:
        request_url = """{}api/v1/applications""".format(argo_host)
        headers = {"Authorization": "Bearer {}".format(argocd_accesstoken)}
        api_response = requests.post(request_url, data=json.dumps(data), headers=headers)

        if api_response.ok:
            response = True
            print(f"argocd 애플리케이션 생성 성공: {project_name}")
        else:
            print("[332] create argocd application is failed: {}".format(api_response.json()))

    except Exception as e:
        print("[332] create argocd application is failed: {}".format(e))
    print(project)
    if request.POST['KIND'] == 'GitHub App':
        return render(request, 'pybo/github.html', context)
    else:
        return render(request, 'pybo/custom.html', context)

mysite/templates/pybo/custom.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<table style="width: 100%;">
    <th>
    <h3 class="projecthead">&nbsp&nbsp Custom Application</h3>
    </th>
    <th>
        <form method='post' class='post-form my-3' action="{% url 'pybo:monitor_list' project.id %}">
            {% csrf_token %}
            <input type="hidden" name="PN" id="PN" value="{{ project.NAME }}"  maxlength="100">
            <button type='submit' class='button-49' role="button" value="Monitor">Monitor</button>
        </form>
    </th>
</table>
<div>
    {% if state == '' %}
    {% else %}
    <script>
        alert('{{ state }}')
    </script>
    {% endif %}
</div>
<div class='container'>
    <h3><strong> Project Name : {{ project.NAME }}</strong></h3>
    <br>
    <div>
        <p><Strong>GitHub Repository</strong></p>
        <p><Strong>{{ project.GIT }}</Strong></p>
        <hr/>
        <table>
            <tr>
                <th style="padding-left: 150px;">
                    <img draggable="false" src="{% static 'jenkins_image.png' %}" style="width:300px; height:220px;">
                    <form method='post' class='post-form my-3' action="{% url 'pybo:jenkins_api' %}">
                        {% csrf_token %}
                        <p><strong>Jenkins Build</strong></p>
                        <p>빌드할 GitHub Repository 주소</p>
                        <p id="gitbox0"><u>{{ project.GIT }}</u></p>
                        <input type="hidden" name="addr" id="addr" value="{{ project.GIT }}"  maxlength="100">
                        <input type="hidden" name="PN" id="PN" value="{{ project.NAME }}"  maxlength="100">
                        <input type="hidden" name="KIND" id="KIND" value="{{ project.KIND }}"  maxlength="100">
                        <input type="hidden" name="PID" id="PID" value="{{ project.id }}"  maxlength="100">
                        <button type="submit" class="button-55" role="button">빌드하기</button>
                    </form>
                    <br>
                    <a draggable="false" href='http://192.168.160.244:8080/job/{{ project.NAME }}/' class="button-89" role="button" target='_blank' style="text-decoration: none;">
                        Jenkins Build 확인
                    </a>
                </th>
                <th style="padding-left: 70px;">
                    <img draggable="false" src="https://us.123rf.com/450wm/alexwhite/alexwhite1503/alexwhite150305065/38145435-%EC%99%BC%EC%AA%BD-%ED%99%94%EC%82%B4%ED%91%9C-%EB%85%B9%EC%83%89-%ED%8F%89%EB%A9%B4-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%99%94%EC%82%B4%ED%91%9C-%EA%B8%B0%ED%98%B8.jpg?ver=6" 
                        style="transform:rotate(180deg); width:75px; height:75px;">
                </th>
                <th style="padding-left: 100px;">
                    <img draggable="false" src="https://blog.kakaocdn.net/dn/skltp/btq8FeXAVbT/kvEk8k4Id91wQ938gq3CYk/img.png" style="width:300px; height:250px;">
                    <form method='post' class='post-form my-3' action="{% url 'pybo:customapp' %}">
                    {% csrf_token %}
                    <p><strong>Argo CD Deploy</strong></p>
                    <p>빌드할 GitHub Repository 주소</p>
                    <p id="gitbox0"><u>{{ project.GIT }}</u></p>
                    <P>Argo CD Repository</P>
                    <input type="text" name="GIT" id="GIT" placeholder="ArgoCD Repository" value="">
                    <input type="hidden" name="ADDR" id="ADDR" value="{{ project.GIT }}"  maxlength="100">
                    <input type="hidden" name="PN" id="PN" value="{{ project.NAME }}"  maxlength="100">
                    <input type="hidden" name="PID" id="PID" value="{{ project.id }}"  maxlength="100">
                    <input type="hidden" name="KIND" id="KIND" value="{{ project.KIND }}"  maxlength="100">
                    <button type="submit" class="button-55" role="button">배포하기</button>
                    </form>
                </th>
            </tr>
        </table>
        <br><br><br>
        <table width="400">
            <!-- <th>
                <a href="{% url 'pybo:jenkins_backup' %}" class="delete btn btn-sm btn-outline-secondary">젠킨스 레포지토리 초기화</a>
            </th> -->
            <th>
                <a draggable="false" href="javascript:void(0)" style="color:red" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:project_delete' project.id %}">프로젝트 삭제</a>
            </th>
        </table>
        
        <script type='text/javascript'>
            const delete_elements = document.getElementsByClassName("delete");
            Array.from(delete_elements).forEach(function(element) {
                element.addEventListener('click', function() {
                    if(confirm("정말로 삭제하시겠습니까?")) {
                        location.href = this.dataset.uri;
                    };
                });
            });
        </script>
{% endblock %}

mysite/templates/pybo/github.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<table style="width: 100%;">
    <th>
        <h3 class="projecthead">&nbsp&nbsp GitHub Application</h3>
    </th>
    <th>
        <form method='post' class='post-form my-3' action="{% url 'pybo:monitor_list' project.id %}">
            {% csrf_token %}
            <input type="hidden" name="PN" id="PN" value="{{ project.NAME }}"  maxlength="100">
            <button type='submit' class='button-49' role="button" value="Monitor">Monitor</button>
        </form>
    </th>
</table>
<div class='container' style="margin-bottom: 100px;">
    <h3><strong>Project Name : {{ project.NAME }}</strong></h3>
    <br><br>    
    <div>
        {% csrf_token %}
        <table>
            <tr>
                <th style="padding-left: 0px;">
                    <img draggable="false" src="https://pbs.twimg.com/profile_images/1414990564408262661/r6YemvF9_400x400.jpg" style="width:200px; height:220px; display: block; margin-left: auto; margin-right: auto;">
                    <p><strong>Git Hub</strong></p>
                    <p>GitHub Repository 주소 : {{ project.GIT }}</p>
                    <form method='get' class='post-form my-3' action="{% url 'pybo:github_listfile' project.id %}">
                        {% csrf_token %}
                        <p><strong>Edit Git Hub</strong></p>
                        <button type="submit" class="button-55" role="button">Git Hub 설정하기</button>
                    </form>
                </th>
                <th style="padding-left: 25px;">
                    <img draggable="false" src="https://us.123rf.com/450wm/alexwhite/alexwhite1503/alexwhite150305065/38145435-%EC%99%BC%EC%AA%BD-%ED%99%94%EC%82%B4%ED%91%9C-%EB%85%B9%EC%83%89-%ED%8F%89%EB%A9%B4-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%99%94%EC%82%B4%ED%91%9C-%EA%B8%B0%ED%98%B8.jpg?ver=6" 
                        style="transform:rotate(180deg); width:75px; height:75px">
                </th>
                <th style="padding-left: 25px; position: relative;">
                    <img draggable="false" src="{% static 'jenkins_image.png' %}" style="width:300px; height:220px; display: inline; margin-left: auto; margin-right: auto;">
                    <p><strong>Jenkins</strong></p>
                    <p>빌드할 GitHub Repository 주소 : {{ project.GIT }}</p>
                    <form method='post' class='post-form my-3' action="{% url 'pybo:jenkins_api' %}">
                        {% csrf_token %}
                        <p><strong>Jenkins Build</strong></p>
                        <input type="hidden" name="addr" id="addr" value="{{ project.GIT }}"  maxlength="100">
                        <input type="hidden" name="KIND" id="KIND" value="{{ project.KIND }}"  maxlength="100">
                        <input type="hidden" name="PN" id="PN" value="{{ project.NAME }}"  maxlength="100">
                        <input type="hidden" name="PID" id="PID" value="{{ project.id }}"  maxlength="100">
                        <button type="submit" class="button-55" role="button">빌드하기</button>
                    </form>
                    <br>
                    <table>
                        <tr>
                            <td style="padding-bottom: 35px;">
                                <a draggable="false" href='http://192.168.160.244:8080/job/{{ project.NAME }}/' class="button-89" role="button" target='_blank' style="text-decoration: none;">Jenkins Build 확인</a>
                            </td>
                        </tr>
                        <tr>
                           <td style="padding-bottom: 35px;">
                                <a draggable="false" href='http://192.168.160.244:9000/dashboard?id={{ project.NAME }}/' class="button-89" role="button" target='_blank' style="text-decoration: none;">Sonarqube 확인</a>
                            </td> 
                        </tr>
                        <tr>
                            <td style="padding-bottom: 35px;">
                                <a draggable="false" href='http://192.168.160.244:8080/blue/organizations/jenkins/{{ project.NAME }}/activity/' class="button-89" role="button" target='_blank' style="text-decoration: none;">Blue Ocean 확인</a>
                            </td>
                        </tr>
                    </table>
                </th>
                <th style="padding-left: 25px; padding-top: 25px;">
                    <img draggable="false" src="https://us.123rf.com/450wm/alexwhite/alexwhite1503/alexwhite150305065/38145435-%EC%99%BC%EC%AA%BD-%ED%99%94%EC%82%B4%ED%91%9C-%EB%85%B9%EC%83%89-%ED%8F%89%EB%A9%B4-%EC%95%84%EC%9D%B4%EC%BD%98-%ED%99%94%EC%82%B4%ED%91%9C-%EA%B8%B0%ED%98%B8.jpg?ver=6" 
                        style="transform:rotate(180deg); width:75px; height:75px">
                </th>
                <th style="padding-left: 25px;">
                    <img draggable="false" src="https://blog.kakaocdn.net/dn/skltp/btq8FeXAVbT/kvEk8k4Id91wQ938gq3CYk/img.png" style="width:250px; height:250px; display: block; margin-left: auto; margin-right: auto;">
                    <div class="info">
                        <p><strong>Argo CD Deploy</strong></p>
                        <p>빌드할 GitHub Repository 주소 : {{ project.GIT }}</p>
                        <form method='post' class='post-form my-3' action="{% url 'pybo:customapp' %}">
                            {% csrf_token %}
                            <p><strong>ArgoCD Deploy</strong></p>
                            <input type="text" name="GIT" id="GIT" placeholder="YAML 파일 위치" value="">
                            <input type="hidden" name="ADDR" id="ADDR" value="{{ project.GIT }}"  maxlength="100">
                            <input type="hidden" name="PN" id="PN" value="{{ project.NAME }}"  maxlength="100">
                            <input type="hidden" name="PID" id="PID" value="{{ project.id }}"  maxlength="100">
                            <input type="hidden" name="KIND" id="KIND" value="{{ project.KIND }}"  maxlength="100">
                            <button type="submit" class="button-55" role="button">배포하기</button>
                        </form>
                    </div>
                    
                </th>
            <tr>
        </table>
        <br><br><br><br><br>
        <table border="0" width="400">
            <!-- <th>
                <a href="{% url 'pybo:jenkins_backup' %}" class="delete btn btn-sm btn-outline-secondary">젠킨스 레포지토리 초기화</a>
            </th> -->
            <th>
                <a draggable="false" href="javascript:void(0)" style="color:red" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:project_delete' project.id %}">프로젝트 삭제</a>
            </th>
        </table>
        <script type='text/javascript'>
            const delete_elements = document.getElementsByClassName("delete");
            Array.from(delete_elements).forEach(function(element) {
                element.addEventListener('click', function() {
                    if(confirm("정말로 삭제하시겠습니까?")) {
                        location.href = this.dataset.uri;
                    };
                });
            });
        </script>
    </div>
</div>
{% endblock %}

mysite/templates/pybo/logging.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="twelve">
    <h2>Logging</h2>
</div>
<div style="padding: 2vw;">
    <iframe src="http://logging.xyz/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(),index:a1f4e340-96d3-11ed-835c-3b733a6de5e6,interval:auto,query:(language:kuery,query:''),sort:!())" style="display:block; width:95vw; height: 78vh" scrolling="yes"></iframe>
</div>
{% endblock %}