mysite/common/urls.py
from urllib.parse import urlparse


from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

mysite/pybo/urls.py
from django.urls import path
from .views import app_views, base_views, customapp_views, gitapp_views, project_views, monitor_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:project_id>/', base_views.detail, name='detail'),
    
    # project_views.py
    path('project/', project_views.project, name='project'),
    path('project/delete/<int:project_id>/', project_views.project_delete, name='project_delete'),
    
    # app_views.py
    path('app/', app_views.app, name='app'),
    path('webapp/', app_views.webapp, name='webapp'),
    path('dbapp/', app_views.dbapp, name='dbapp'),

    # custom_views.py
    path('jenkins_api/', customapp_views.jenkins_api, name='jenkins_api'),
    path('jenkins_backup/', customapp_views.jenkins_backup, name='jenkins_backup'),
    path('customapp/', customapp_views.customapp, name='customapp'),

    # gitapp_views.py
    path('docker/<int:project_id>/', gitapp_views.docker, name='docker'),
    path('docker/create/<int:project_id>', gitapp_views.create_jenkins, name='create_jenkins'),
    path('YAML/<int:project_id>/', gitapp_views.argocd, name='argocd'),
    path('github_list/<int:project_id>/', gitapp_views.github_listfile, name='github_listfile'),
    path('github_list/create/<int:project_id>', gitapp_views.github_createfile, name='github_createfile'),
    path('github_list/edit/<int:project_id>', gitapp_views.github_editfile, name='github_editfile'),
    path('github_list/delete/<int:project_id>', gitapp_views.github_deletefile, name='github_deletefile'),

    # monitor_views.py
    path('monitor/<int:project_id>', monitor_views.monitor_list, name='monitor_list'),
    path('logging/', monitor_views.logging, name='logging'),
    path('grafana/', monitor_views.grafana, name='grafana'),
]

mysite/common/models.py
from django.db import models

# Create your models here.

mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    
    class Meta:
        model = User
        fields = ("username", "email")

mysite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
    </div>
    <form method="post" action = "{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
        <div class="col-8 text-right">
            <br>
            <span>
                또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a>
            </span>
        </div>
    </form>
</div>
{% endblock %}

mysite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}